### ISSUE TITLE
how do we avoid editorializing issues?

### ISSUE THREAD

**Issue by sodiumjoe** [sodiumjoe/action#2]
The consensus appears to be that the platform should be a neutral party. The only way I can think of to maintain that is to pass all editorializing to the advocacy groups, and pass off responsibility for knowing which advocacy groups to follow to the users.

```
Subscribe:
[ ] Greanpeace
  [ ] Climate change
  [ ] Corporate pollution
  [ ] Endangered habitats
```

**Comment by strunkandwhite** [comment]
How do we choose which advocacy groups to allow users to follow? Isn't that process itself editorialization? And I'm not just trying to be difficult, I really think that offering a broad range of options is critical to conveying that we really are neutral. Maybe we offer anything that meets a simple set of guidelines, like:

- No hate speech
- Fact-based arguments
- Not obvious extensions of multinational corporations (e.g. Heartland Institute)

**Comment by edhille** [comment]
I didn't realize we'd be integrating advocacy group information.  My thinking was that we would hopefully get all the data we need from non-partisan groups that simply aggregate government data.

**Comment by sodiumjoe** [comment]
decided to punt on this for the [initial prototype](https://github.com/sodiumjoe/action/milestone/1) and simply notify users of all impending legislation/committee action that involves their local representatives
