### ISSUE TITLE
DBConnection.ConnectionError when running mix ecto.create

### ISSUE THREAD

**Issue by edhille** [sodiumjoe/action#6]
I get this:
14:28 $ mix ecto.create

14:28:18.826 [error] GenServer #PID<0.181.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Action.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

Assuming I'm missing a step to get the db host running on port 5432?

**Comment by sodiumjoe** [comment]
Yeah, you need to run `postgres` locally:

```bash
brew install postgres
pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
createuser -d postgres
```

added to the readme
