### ISSUE TITLE
think of a good name

### ISSUE THREAD

**Issue by sodiumjoe** [sodiumjoe/action#8]

**Comment by edhille** [comment]
CitizenLobbyist

**Comment by sodiumjoe** [comment]
I feel like "lobbyist" has some negative connotations, but I can't think of anything better.

**Comment by jondlm** [comment]
I agree it has a weird connotation, though I don't currently have anything better either.

**Comment by edhille** [comment]
I agree Lobbyist has bad connotations, but the act of calling your congressperson to advocate for what you believe this country should do is lobbying. One of the definitions literally is "campaign for, crusade for, press for, push for, ask for, call for, demand".

This is intended to help citizens get their voice heard and there will be no confusion that this app is for citizens to demand something from their government.  I know we've talked about SpeakUp and HearUS as good candidates as well and I think they are great, but they are less direct about the essential purpose of this app

Sometimes you have to take back a word that others have sullied.

**Comment by jondlm** [comment]
After some pondering, I'm good with CitizenAdvocate

**Comment by sodiumjoe** [comment]
just bought `citizen-advocate.org`
